[package]
name = "rust-gd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
bitvec = "1.0.0"
hashlink = "0.7.0"
libecc = { path = "src/libecc", version = "0.1.0" }

[dev-dependencies]
rand = "0.8.5"
